apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-acme-challenge
  labels:
{{ include "cas-ggircs.labels" . | indent 4 }}

spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 25Mi
  storageClassName: {{ .Values.app.route.ssl.storageClassName }}
