{{- $sessionSecret := (randAlphaNum 32) | b64enc | quote }}
{{- $dbAppPassword := (randAlphaNum 32) | b64enc | quote }}
{{- $secretName := print (include "cas-ggircs.fullname" .) "-app" }}

{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- if $secret }}
{{- $sessionSecret = index $secret.data "session-secret" }}
{{- $dbAppPassword = index $secret.data "database-app-password" }}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "cas-ggircs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  session-secret: {{ $sessionSecret }}
  database-app-user: {{ .Values.persistence.appUser | b64enc | quote }}
  database-app-password: {{ $dbAppPassword }}
