apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cas-ggircs.fullname" . }}
  labels:
{{ include "cas-ggircs.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  session-secret: {{ randAlphaNum 32 | b64enc | quote }}
  database-app-user: {{ .Values.persistence.appUser | b64enc | quote }}
  database-app-password: {{ randAlphaNum 32 | b64enc | quote }}