-- Deploy ggircs:table_fuel_mapping to pg
-- requires: schema_ggircs_swrs

begin;

create table ggircs_swrs_load.fuel_mapping (
  id integer generated always as identity primary key,
  fuel_type varchar(1000),
  fuel_carbon_tax_details_id integer

);

comment on table  ggircs_swrs_load.fuel_mapping is 'DEPRECATED The fuel mapping table that maps fuel type with carbon tax rates';
comment on column ggircs_swrs_load.fuel_mapping.id is 'The internal primary key for the mapping';
comment on column ggircs_swrs_load.fuel_mapping.fuel_type is 'The type of fuel (from GHGR), Foreign key to fuel';
comment on column ggircs_swrs_load.fuel_mapping.fuel_carbon_tax_details_id is 'The foreign key to ggircs_swrs_load.fuel_carbon_tax_details';


create unique index ggircs_swrs_fuel_mapping_fuel_type on ggircs_swrs_load.fuel_mapping(fuel_type);

INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Acetylene', 1);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Acetylene (Sm^3)', 1);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Agricultural Byproducts (bone dry tonnes)', 2);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Anthracite Coal (tonnes)', 3);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Asphalt & Road Oil (kilolitres)', 4);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Aviation Gasoline (kilolitres)', 5);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Aviation Turbo Fuel (kilolitres)', 6);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Biodiesel (100)', 7);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Biodiesel (100) (kilolitres)', 7);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Biodiesel (100%) (kilolitres)', 7);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Biogas (captured methane) (Sm^3)', 8);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Bituminous Coal', 9);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Bituminous Coal (tonnes)', 9);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Bone char - organics', 10);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Bone char - organics (tonnes)', 10);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Butane (kilolitres)', 11);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Butylene (kilolitres)', 12);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('C/D Waste - Plastic (tonnes)', 13);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('C/D Waste - Wood (tonnes)', 14);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Cloth (tonnes)', 15);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('CNCG', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('CNCGs (Sm^3)', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Coal Coke (tonnes)', 17);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Coal/PetCoke  blend (tonnes)', 18);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Coke Oven Gas (Sm^3)', 19);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Combustible Tall Oil', 20);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Combustible Tall Oil (kilolitres)', 20);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated non-condensable gases (CNCGs)', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated Non-condensible Gas', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated Non-condensable Gases', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated Non-condensible Gases', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated Non-Condensible Gases (CNCG)', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated non-condensible gases (CNCGs)', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated non-condensible gases (CNCGs) (Sm^3)', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Concentrated non-condensible gases from kraft process', 16);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Crude Oil (kilolitres)', 21);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Crude Sulfate Turpentine (CST)', 22);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Crude Sulfate Turpentine (CST) (kilolitres)', 22);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Crude Tall Oil (CTO)', 23);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Crude Tall Oil (CTO) (kilolitres)', 23);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Diesel', 24);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Diesel (kilolitres)', 24);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Digester Gas', 25);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Digester Gas (Sm^3)', 25);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Dilute non-condensable gases (DNCGs)', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Dilute Non-condensible Gas', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Dilute non-condensible gases (DNCGs)', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Dilute non-condensible gases (DNCGs) (Sm^3)', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Dilute non-condensible gases from kraft process', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Distilate Fuel Oil No.1', 26);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Distilate Fuel Oil No.1 (kilolitres)', 26);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Distilate Fuel Oil No.2', 27);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Distilate Fuel Oil No.2 (kilolitres)', 27);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Distilate Fuel Oil No.4 (kilolitres)', 28);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('DNCG', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('DNCG''s', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('DNCGs (Sm^3)', 29);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('E-Waste', 33);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('E-Waste (tonnes)', 33);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Ethane (kilolitres)', 30);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Ethanol (100%) (kilolitres)', 31);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Ethylene (kilolitres)', 32);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Explosives', 34);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Explosives (tonnes)', 34);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Field Gas', 36);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Field Gas (Sm^3)', 36);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Field gas or process vent gas', 35);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Field gas or process vent gas  (Sm^3)', 35);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Foreign Bituminous Coal (tonnes)', 37);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Isobutane (kilolitres)', 38);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Isobutylene (kilolitres)', 39);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Kerosene', 40);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Kerosene (kilolitres)', 40);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Kerosene-type Jet Fuel (kilolitres)', 41);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Landfill Gas', 42);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Landfill Gas (Sm^3)', 42);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Light Fuel Oil', 43);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Light Fuel Oil (kilolitres)', 43);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Lignite (tonnes)', 44);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Liquified Petroleum Gases (LPG)', 45);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Liquified Petroleum Gases (LPG) (kilolitres)', 45);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Lubricants', 46);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Lubricants (kilolitres)', 46);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Motor Gasoline', 47);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Motor Gasoline - Off-Road (kilolitres)', 48);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Motor Gasoline (kilolitres)', 47);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Municipal Solid Waste - biomas', 49);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Municipal Solid Waste - biomass component', 49);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Municipal Solid Waste - biomass component (bone dry tonnes)', 49);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Municipal Solid Waste - non-bi', 50);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Municipal Solid Waste - non-biomass component', 50);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Municipal Solid Waste - non-biomass component (tonnes)', 50);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Naphtha', 51);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Naphtha (kilolitres)', 51);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Natural Gas', 53);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Natural Gas (Sm^3)', 53);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Natural Gasoline', 52);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Natural Gasoline (kilolitres)', 52);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Nitrous Oxide', 54);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Nitrous Oxide (Sm^3)', 54);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Peat (tonnes)', 55);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('PEF (tonnes)', 56);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Petrochemical Feedstocks (kilolitres)', 57);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Petroleum Coke', 58);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Petroleum Coke - Refinery Use (kilolitres)', 59);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Petroleum Coke (kilolitres)', 58);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Plastic (tonnes)', 60);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Propane ', 61);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Propane', 61);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Propane (kilolitres)', 61);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Propylene (kilolitres)', 62);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Refinery Fuel Gas', 63);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Refinery Fuel Gas (Sm^3)', 63);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Rendered Animal Fat (kilolitres)', 64);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Residual Fuel Oil (#5 & 6)', 65);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Residual Fuel Oil (#5 & 6) (kilolitres)', 65);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('RFG - Mix Drum', 66);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('RFG - Reformer Gas', 67);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Roofing Tear-off (tonnes)', 68);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('SMR PSA Tail Gas', 69);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('SMR PSA Tail Gas (Sm^3)', 69);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Sodium Bicarbonate', 70);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Sodium Bicarbonate (tonnes)', 70);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Solid Byproducts', 71);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Solid Byproducts (bone dry tonnes)', 71);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Spent Pulping Liquor', 72);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Spent Pulping Liquor (bone dry tonnes)', 72);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Still Gas', 74);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Still Gas - Refineries (Sm^3)', 73);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Still Gas (Sm^3)', 74);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Sub-Bituminous Coal', 75);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Sub-Bituminous Coal (tonnes)', 75);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Tail Gas (Sm^3)', 76);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Tall Oil (kilolitres)', 77);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Tires - biomass component (bone dry tonnes)', 78);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Tires - non-biomass component', 79);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Tires - non-biomass component (tonnes)', 79);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Trona (tonnes)', 80);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Turpentine', 81);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Turpentine (kilolitres)', 81);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Vegetable Oil (kilolitres)', 82);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Waste Oil (kilolitres)', 83);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Wood Waste', 84);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Wood Waste (bone dry tonnes)', 84);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Flared Natural Gas CO2', 85);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Flared Natural Gas CH4', 86);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Flared Natural Gas N2O', 87);
INSERT INTO ggircs_swrs_load.fuel_mapping (fuel_type, fuel_carbon_tax_details_id) VALUES ('Vented Natural Gas', 88);

commit;
