cas-postgres:
  patroni:
    walE:
      enable: true
      gcsBucket: wksv3k-prod-ggircs-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-wksv3k-prod-ggircs-backups-service-account-key
    # options below are required if walE.enable is true
  namespace: wksv3k-prod
  gcs:
    bucketSuffix: ggircs-backups
