cas-postgres:
  patroni:
    walE:
      enable: true
      gcsBucket: 9212c9-prod-ggircs-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-9212c9-prod-ggircs-backups-service-account-key
    # options below are required if walE.enable is true
  namespace: 9212c9-prod
  gcs:
    bucketSuffix: ggircs-backups

app:
  route:
    host: cas-ggircs.apps.silver.devops.gov.bc.ca

download-ggircs-dags:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

download-swrs-dags:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

trigger-ggircs-deploy-db:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

nginx-sidecar:
  hostName: cas-ggircs.apps.silver.devops.gov.bc.ca

patroni-migration:
  from:
    host: cas-ggircs-patroni.9212c9-prod.svc.cluster.local
