cas-postgres:
  patroni:
    walE:
      enable: true
      gcsBucket: 9212c9-test-ggircs-backups
      # kubernetesSecret should be gcp-{{ namespace }}-{{ gcs.bucketSuffix }}-service-account-key
      kubernetesSecret: gcp-9212c9-test-ggircs-backups-service-account-key
    # options below are required if walE.enable is true
  namespace: 9212c9-test
  gcs:
    bucketSuffix: ggircs-backups

app:
  route:
    host: cas-ggircs-test.apps.silver.devops.gov.bc.ca

download-ggircs-dags:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca

trigger-ggircs-deploy-db:
  airflowEndpoint: https://cas-airflow-test.apps.silver.devops.gov.bc.ca
