app:
  route:
    host: cas-ggircs.apps.silver.devops.gov.bc.ca

download-ggircs-dags:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

download-swrs-dags:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

trigger-ggircs-deploy-db:
  airflowEndpoint: https://cas-airflow-prod.apps.silver.devops.gov.bc.ca

nginx-sidecar:
  hostName: cas-ggircs.apps.silver.devops.gov.bc.ca
