apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-db-init
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            name: {{ template "cas-ggircs.fullname" . }}-db-init
        spec:
          restartPolicy: Never
          containers:
            - env:
                - name: PGDATABASE
                  value: postgres
                - name: PGUSER
                  value: postgres
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password-superuser
                      name: {{ template "cas-ggircs.fullname" . }}-patroni
                - name: PGPORT
                  value: "5432"
                - name: PGHOST
                  value: {{ template "cas-ggircs.fullname" . }}-patroni
                - name: GGIRCS_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: GGIRCS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: GGIRCS_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: {{ template "cas-ggircs.fullname" . }}
              name: {{ template "cas-ggircs.fullname" . }}-db-init
              image: {{ .Values.image.psql.repository }}:{{ .Values.image.psql.tag }}
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command: [ "create-user-db" ]
              args: [
                "-d", "$(GGIRCS_DATABASE)",
                "-u", "$(GGIRCS_USER)",
                "-p", "$(GGIRCS_PASSWORD)",
                "--owner"
              ]
