{{- if .Values.swrsImportBucket.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-swrs-import-bucket-provider
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ template "cas-ggircs.fullname" . }}-swrs-import-bucket-provider
      labels: {{ include "cas-ggircs.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ template "cas-ggircs.fullname" . }}-swrs-import-bucket-provider
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: {{ .Values.image.casShelf.repository }}:{{ .Values.image.casShelf.tag }}
          imagePullPolicy: {{ .Values.image.casShelf.pullPolicy }}
          env:
            - name: TFC_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: terraform-cloud-workspace
            - name: TFC_WORKSPACE_ID
              valueFrom:
                secretKeyRef:
                  key: workspace_id
                  name: terraform-cloud-workspace
          command: ["bash",  "/script.sh", {{ .Release.Namespace | quote }}, {{ .Values.swrsImportBucket.bucketSuffix | quote }}]
      restartPolicy: Never
{{- end }}
