exclude: >
  (?x)^(
      test\.js\.snap$|
      stories\.storyshot$
  )$
repos:
  - repo: local
    hooks:
      - id: yarn-format
        name: Fix formatting and lint with prettier and eslint
        language: script
        files: ggircs-app\/app\/.*\.(j|t)sx?$
        entry: ./.bin/format.sh
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-vcs-permalinks
      - id: check-yaml
        exclude: ^helm/.*/templates/
      - id: end-of-file-fixer
        exclude: current_version\.txt|CHANGELOG\.md
      - id: trailing-whitespace
        exclude: .*/tests/.*
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.19.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.12.0
    hooks:
      - id: gitlint
