kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata: 
  name: {{ include "cas-ggircs.fullname" . }}-postgres-data-warehouse-ingress
  labels: {{ include "cas-ggircs.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.database.releaseName }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: cas-data-warehouse
      namespaceSelector:
        matchLabels:
          environment: {{ .Values.environment }}
          name: 09269b
