apiVersion: v1
kind: Service
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-swrs-gcp-api
  labels: {{ include "cas-ggircs.labels" . | nindent 4 }}

spec:
  ports:
  - name: {{ template "cas-ggircs.fullname" . }}
    port: {{ .Values.swrsGcpApi.port }}
    protocol: TCP
    targetPort: {{ .Values.swrsGcpApi.port }}
  selector: {{ include "cas-ggircs.selectorLabels" . | nindent 4 }}
    component: swrs-gcp-api
  sessionAffinity: None
  type: ClusterIP
