version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0
  gcp-gcr: circleci/gcp-gcr@0.7.1
  helm: circleci/helm@0.2.3
jobs:
  test:
    docker:
      - image: wenzowski/sqitch:0.9999
      - image: wenzowski/postgres:11.2
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init
      - run:
          name: Create testing db
          command: |
            RETRIES=5
            until psql -h localhost -U postgres -d postgres -c "select 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
              echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
              sleep 1
            done
            createuser sqitch  -U postgres -h localhost
            createdb -O sqitch sqitch -U postgres -h localhost
            createdb -O sqitch ggircs_test -U postgres -h localhost
      - run:
          name: Test database using Make
          command: make test PSQL="psql -h localhost" CI_NO_PIPELINE=true

  test-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - checkout
      - run:
          name: "Checkout Submodules"
          command: |
            git submodule update --init
      - run:
          name: Add Docker registry to /etc/hosts
          command: echo "172.30.1.1 docker-registry.default.svc" | sudo tee -a /etc/hosts
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true

      - run:
          command: docker login -u "$RED_HAT_DOCKER_USERNAME" -p "$RED_HAT_DOCKER_PASSWORD" "$RED_HAT_DOCKER_SERVER"
          name: Log in to Red Hat docker registry
      - run:
          name: Login as cluster admin
          command: oc login -u system:admin
      - run:
          command: make mock_storageclass
          name: Mock the storage classes
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 4.x
          password: password
          server-address: "https://127.0.0.1:8443"
          username: dev1
      - run:
          command: make provision
          name: Provision the cluster project set
      - helm/install-helm-client:
          version: v3.4.2
      - run:
          command: |
            helm dep up ./helm/cas-ggircs
            helm install --atomic --timeout 900s --namespace "9212c9-dev" \
            --set image.etl.tag="$CIRCLE_SHA1" \
            --set cas-postgres.patroni.walE.enable=false \
            --set networkSecurityPolicies.enable=false \
            cas-ggircs ./helm/cas-ggircs
          name: Deploy to dev
      - run:
          command: |
            oc -n 9212c9-dev get all
          name: Print namespace contents
      - run:
          command: |
            helm test cas-ggircs --timeout 1200s --namespace "9212c9-dev"
          name: Test helm chart
          no_output_timeout: 21m

  lint:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - helm/install-helm-client:
          version: v3.2.1
      - run:
          command: helm lint ./helm/cas-ggircs
          name: Lint the helm charts

  build:
    executor: gcp-gcr/default
    parameters:
      image_tag:
        type: string
      cache_version:
        type: integer
        default: 2
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - restore_cache:
          keys:
            - v<< parameters.cache_version>>-cas-ggircs-etl-{{ .Branch }}
          paths:
            - /tmp/cas-ggircs-etl.tar
      - run:
          name: Load cache
          command: |
            set +o pipefail
            docker load -i /tmp/cas-ggircs-etl.tar | true
      - run:
          name: Log in to DockerHub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin registry.hub.docker.com
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=cas-ggircs-etl -t cas-ggircs-etl:latest -t gcr.io/${GOOGLE_PROJECT_ID}/cas-ggircs-etl:<< parameters.image_tag >> .
      - run:
          name: Save Docker image layer cache
          command: |
            docker save -o /tmp/cas-ggircs-etl.tar cas-ggircs-etl:latest
      - save_cache:
          key: v<< parameters.cache_version>>-cas-ggircs-etl-{{ .Branch }}-{{ epoch }}
          paths:
            - /tmp/cas-ggircs-etl.tar
      - gcp-gcr/push-image:
          image: cas-ggircs-etl
          tag: << parameters.image_tag >>
          digest-path: /tmp/digest.txt
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  version: 2
  test:
    jobs:
      - test
      - lint:
          filters:
            tags:
              only: /^v.*/
      - build:
          context: cas-pipeline
          image_tag: ${CIRCLE_SHA1}
          requires:
            - lint
      - test-local-cluster:
          context: cas-pipeline
          requires:
            - build
      - build:
          name: build_tag
          context: cas-pipeline
          image_tag: ${CIRCLE_TAG/v/}
          requires:
            - lint
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/a00d3135-7e96-47a0-817e-0086ec993205@55bc71c2-5150-4ff8-bbcd-d94bc32bf20c/CircleCI/4dd288af085245bf96cc07dce642e3ed/c436c63a-5475-4837-ae24-c21c300bd4e1
