version: 2.1

orbs:
  redhat-openshift: circleci/redhat-openshift@0.2.0

jobs:
  test:
    docker:
      - image: wenzowski/sqitch:0.9999
      - image: wenzowski/postgres:11.2
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init
      - run:
          name: Create testing db
          command: |
            RETRIES=5
            until psql -h localhost -U postgres -d postgres -c "select 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
              echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
              sleep 1
            done
            createuser sqitch  -U postgres -h localhost
            createdb -O sqitch sqitch -U postgres -h localhost
            createdb -O sqitch ggircs_test -U postgres -h localhost
      - run:
          name: Test database using Make
          command: make test PSQL="psql -h localhost" CI_NO_PIPELINE=true

  test-local-cluster:
    executor: redhat-openshift/machine-for-local-cluster
    steps:
      - checkout
      - run:
          name: "Checkout Submodules"
          command: |
            git submodule update --init
      - run:
          name: Add Docker registry to /etc/hosts
          command: echo "172.30.1.1 docker-registry.default.svc" | sudo tee -a /etc/hosts
      - redhat-openshift/create-local-cluster-with-oc:
          skip-registry-check: true

      - run:
          command: docker login -u "$RED_HAT_DOCKER_USERNAME" -p "$RED_HAT_DOCKER_PASSWORD" "$RED_HAT_DOCKER_SERVER"
          name: Log in to Red Hat docker registry
      - run:
          name: Login as cluster admin
          command: oc login -u system:admin
      - run:
          command: make mock_storageclass
          name: Mock the storage classes
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          password: password
          server-address: 'https://127.0.0.1:8443'
          username: dev1
      - run:
          command: make provision
          name: Provision the cluster project set
      - run:
          command: make configure
          name: Configure the cluster
      - run:
          command: make build
          name: Build image on the cluster
      - run:
          name: install helm
          command: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
            chmod 700 get_helm.sh
            ./get_helm.sh
      - run:
          command: |
            helm dep up ./helm/cas-ggircs
            helm install --atomic --timeout 900s --namespace "wksv3k-dev" --set image.etl.tag="$CIRCLE_SHA1" cas-ggircs ./helm/cas-ggircs
          name: Deploy to dev
      - run:
          command: |
            oc -n wksv3k-dev get all
          name: Print namespace contents
      - run:
          command: |
            helm test cas-ggircs
          name: Test helm chart


  lint:
    executor: redhat-openshift/default
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          server-address: $OC_SERVER_ADDRESS
          token: $OC_TOKEN
      - run:
          command: make lint CI_NO_POSTGRES=true
          name: Lint the openshift yaml

  build:
    executor: redhat-openshift/default
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --init
      - redhat-openshift/login-and-update-kubeconfig:
          insecure-skip-tls-verify: true
          openshift-platform-version: 3.x
          server-address: $OC_SERVER_ADDRESS
          token: $OC_TOKEN
      - run:
          command: make configure CI_NO_POSTGRES=true
          name: Configure imagestream to point at the current SHA1
      - run:
          command: make build CI_NO_POSTGRES=true
          name: Build image on the remote cluster


workflows:
  version: 2
  test:
    jobs:
      - test
      - lint:
          context: cas-pipeline
      - build:
          context: cas-pipeline
          requires:
            - lint
      - test-local-cluster:
          context: cas-pipeline

notify:
  webhooks:
    - url: https://outlook.office.com/webhook/a00d3135-7e96-47a0-817e-0086ec993205@55bc71c2-5150-4ff8-bbcd-d94bc32bf20c/CircleCI/4dd288af085245bf96cc07dce642e3ed/c436c63a-5475-4837-ae24-c21c300bd4e1
