version: 2
jobs:
  build:
    docker:
      - image: wenzowski/sqitch:0.9999
      - image: postgres:11.2

    steps:
      - checkout

      - run:
          name: Create testing db
          command: |
            RETRIES=5
            until psql -h localhost -U postgres -d postgres -c "select 1" > /dev/null 2>&1 || [ $RETRIES -eq 0 ]; do
              echo "Waiting for postgres server, $((RETRIES--)) remaining attempts..."
              sleep 1
            done
            createuser sqitch  -U postgres -h localhost
            createdb -O sqitch ggircs_test -U postgres -h localhost

      - run:
          name: Test database using Make
          command: make test
