apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs:${GIT_SHA}
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: ${GIT_SHA}
        uri: https://github.com/bcgov/cas-ggircs.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: cas-ggircs-perl:${PERL_VERSION}
      type: Source
    triggers:
    - github:
        secret: cas-ggircs-github-trigger
      type: GitHub
    - generic:
        secret: cas-ggircs-generic-trigger
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange

parameters:

- description: Version of Perl image to be used (latest for now).
  displayName: Version of Perl Image
  name: PERL_VERSION
  required: true
  value: "latest"

- description: Git source code commit currently deployed.
  displayName: Git Short sha
  name: GIT_SHA
  required: true
