apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs-metabase-builder
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs-metabase-builder:${GIT_BRANCH_NORM}
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: https://github.com/bcgov/cas-ggircs.git
      contextDir: docker/metabase-builder
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - generic:
        secret: cas-ggircs-metabase-builder-generic-trigger
      type: Generic
    - github:
        secret: cas-ggircs-metabase-builder-github-trigger
      type: GitHub

parameters:
- description: Git source code branch currently deployed.
  displayName: Git branch
  name: GIT_BRANCH
  required: true
- description: Git source code branch currently deployed, where slashes are replaced by dashes, to be able to use it in image tags.
  displayName: Git branch (normalized)
  name: GIT_BRANCH_NORM
  required: true
