apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs-metabase
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs-metabase:${GIT_BRANCH}
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: https://github.com/bcgov/cas-ggircs.git
      contextDir: docker/metabase
      images:
      - from:
          kind: ImageStreamTag
          name: cas-ggircs-metabase-build:${GIT_BRANCH}
        paths:
        - destinationDir: .
          sourcePath: /opt/app-root/src/cas-ggircs-metabase/target/uberjar/metabase.jar
    strategy:
      type: Docker
    triggers:
    - type: ConfigChange
    - generic:
        secret: cas-ggircs-metabase-generic-trigger
      type: Generic
    - imageChange:
      type: ImageChange
    - github:
        secret: cas-ggircs-metabase-github-trigger
      type: GitHub

parameters:

- description: Git source code branch currently deployed.
  displayName: Git Branch
  name: GIT_BRANCH
  required: true

