apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs-metabase-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs-metabase-build:${GIT_BRANCH}
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: master
        uri: https://github.com/bcgov/cas-ggircs-metabase.git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: cas-ggircs-metabase-builder:latest
      type: Source
    triggers:
    - type: ConfigChange
    - generic:
        secret: cas-ggircs-metabase-generic-trigger
      type: Generic
    - type: ImageChange
      imageChange: {}
    - github:
        secret: cas-ggircs-metabase-github-trigger
      type: GitHub

parameters:

- description: Git source code branch currently deployed.
  displayName: Git Branch
  name: GIT_BRANCH
  required: true
