apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs-metabase-preview-build
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs-metabase-build:${METABASE_VERSION}
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: ${METABASE_VERSION}
        uri: https://github.com/metabase/metabase.git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: cas-ggircs-metabase-builder:${GIT_BRANCH_NORM}
        incremental: true
      type: Source
    triggers:
    - type: ImageChange
      imageChange: {}

parameters:
- description: Git source code branch currently deployed, where slashes are replaced by dashes, to be able to use it in image tags.
  displayName: Git branch (normalized)
  name: GIT_BRANCH_NORM
  required: true
- description: Git tag of the metabase version
  displayName: Metabase version
  name: METABASE_VERSION
  required: true
  value: v0.33.0-RC1
