apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: cas-ggircs-portal
  spec:
    ports:
    - name: cas-ggircs-portal
      nodePort: 0
      port: 3004
      protocol: TCP
      targetPort: 3004
    selector:
      name: cas-ggircs-portal
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

