{{- if .Values.airflowDagTrigger.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-dag-trigger
  labels:
    release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 4 }}
{{- if .Release.IsUpgrade }}
# This job requires the cas-postgres dependency to be running,
# and is required for the app deployment to become ready.
# Therefore, it needs to be part of the initial install (instead of a pre/post install hook)
# For upgrades, it needs to be a hook so that the delete policy kicks in
# and the previous job template gets deleted (as editing job templates is not allowed)
# It can be a hook during upgrades as the cas-postgres dependency will already be running
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
{{- end }}
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 1200
  template:
    metadata:
      name: {{ template "cas-ggircs.fullname" . }}-dag-trigger
      labels:
        release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 8 }}
    spec:
      activeDeadlineSeconds: 1200
      restartPolicy: Never
      containers:
      - name: {{ template "cas-ggircs.fullname" . }}-dag-trigger
        image: {{ .Values.image.etl.repository }}:{{ .Values.image.etl.tag }}
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: {{ .Values.image.etl.pullPolicy }}
        env:
          - name: AIRFLOW_USERNAME
            value: cas-airflow-admin
          - name: AIRFLOW_PASSWORD
            valueFrom:
              secretKeyRef:
                key: default-user-pass
                name: airflow-default-user-password
          - name: RELEASE_SUFFIX
            value: {{ include "cas-ggircs.namespaceSuffix" . }}
        command:
          - /usr/bin/env
          - bash
          - -c
          - ./.bin/trigger-airflow-dag.sh {{ .Values.airflowDagTrigger.name }}
{{- end }}
          