apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-db-create-readonly-user
  labels:
    release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            name: {{ template "cas-ggircs.fullname" . }}-db-create-readonly-user
            release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - env:
                {{- include "cas-ggircs.databaseEnvVars.postgresUser" . | nindent 16 }}
                - name: PGDATABASE
                  value: postgres
                  valueFrom: null
                - name: GGIRCS_READONLY_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-readonly-user
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: GGIRCS_READONLY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-readonly-password
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: GGIRCS_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: {{ template "cas-ggircs.fullname" . }}
              name: {{ template "cas-ggircs.fullname" . }}-db-create-readonly-user
              image: {{ .Values.image.psql.repository }}:{{ default .Values.defaultImageTag .Values.image.psql.tag }}
              imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.psql.pullPolicy }}
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command: [ "create-user-db" ]
              args: [
                "-d", "$(GGIRCS_DATABASE)",
                "-u", "$(GGIRCS_READONLY_USER)",
                "-p", "$(GGIRCS_READONLY_PASSWORD)",
                "--schemas", "swrs,swrs_extract,swrs_history,ggircs_parameters",
                "--privileges", "select"
              ]
