apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-eccc-extract-xml-files
  labels:
    release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 172800
      template:
        metadata:
          labels:
            name: {{ template "cas-ggircs.fullname" . }}-eccc-extract-xml-files
            release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGPORT
                  value: "5432"
                - name: PGHOST
                  value: {{ template "cas-ggircs.fullname" . }}-patroni
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: bucket_name
                      name: gcp-{{ .Release.Namespace }}-{{ .Values.swrsImportBucket.bucketSuffix }}-service-account-key
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /app/gcs/viewer_credentials.json
                - name: ECCC_ZIP_PASSWORDS
                  valueFrom:
                    secretKeyRef:
                      key: zip_passwords
                      name: eccc-swrs-import
              name: {{ template "cas-ggircs.fullname" . }}-eccc-extract-xml-files
              image: {{ .Values.image.ecccExtract.repository }}:{{ .Values.image.ecccExtract.tag }}
              imagePullPolicy: {{ .Values.image.ecccExtract.pullPolicy }}
              command: ["python"]
              args: ["extract_xml_files.py"]
              volumeMounts:
                - name: gcs-credentials
                  mountPath: /app/gcs
                  readOnly: true
              resources:
                limits:
                  cpu: 1000m
                  memory: 2Gi
                requests:
                  cpu: 300m
                  memory: 1Gi
          volumes:
            - name: gcs-credentials
              secret:
                secretName: gcp-{{ .Release.Namespace }}-{{ .Values.swrsImportBucket.bucketSuffix }}-service-account-key
