apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-etl-revert
  labels:
    release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            name: {{ template "cas-ggircs.fullname" . }}-etl-revert
            release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - env:
                - name: SQITCH_TARGET
                  value: "db:pg:"
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGPORT
                  value: "5432"
                - name: PGHOST
                  value: {{ template "cas-ggircs.fullname" . }}-patroni
                - name: SQITCH_FULLNAME
                  value: OpenShift Deployer
                - name: SQITCH_EMAIL
                  value: deployer@pathfinder.gov.bc.ca
              name: {{ template "cas-ggircs.fullname" . }}-etl-revert
              image: {{ .Values.image.etl.repository }}:{{ default .Values.defaultImageTag .Values.image.etl.tag }}
              imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.etl.pullPolicy }}
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  sqitch revert swrs/extract/table/eccc_xml_file -y;
