apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-ghg-credentials-issuer
  labels:
    release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 4 }}
spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 3600
      template:
        metadata:
          labels:
            name: {{ template "cas-ggircs.fullname" . }}-ghg-credentials-issuer
            release: {{ .Release.Name }}
{{ include "cas-ggircs.labels" . | indent 12 }}
        spec:
          restartPolicy: Never
          containers:
            - env:
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: {{ template "cas-ggircs.fullname" . }}
                - name: PGPORT
                  value: "5432"
                - name: PGHOST
                  value: {{ template "cas-ggircs.fullname" . }}-patroni
                - name: ISSUER_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api-key
                      name: ghg-credential-issuer
              name: {{ template "cas-ggircs.fullname" . }}-ghg-credentials-issuer
              image: {{ .Values.image.ghgCredentialsIssuer.repository }}:{{ default .Values.defaultImageTag .Values.image.ghgCredentialsIssuer.tag }}
              imagePullPolicy: {{ default .Values.defaultImagePullPolicy .Values.image.ghgCredentialsIssuer.pullPolicy }}
              command: ["python"]
              args:
                - issue.py
                - "-e"
                - {{ template "cas-ggircs.namespaceSuffix" . }}
                - "-i"
                - "$(ISSUER_API_KEY)"
              resources:
                limits:
                  cpu: 100m
                  memory: 124Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
