apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: cas-ggircs-portal
  spec:
    replicas: 2
    selector:
      name: cas-ggircs-portal
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: cas-ggircs-portal
      spec:
        containers:
        - capabilities: {}
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: database-connection-string
                name: cas-ggircs-postgres
          image: cas-ggircs-portal-mirror:latest
          imagePullPolicy: IfNotPresent
          name: cas-ggircs-portal
          ports:
          - containerPort: 3004
            protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cas-ggircs-portal
        from:
          kind: ImageStreamTag
          name: cas-ggircs-portal-mirror:latest
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}

