apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template
objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: cas-ggircs-metabase-preview
  spec:
    replicas: 2
    selector:
      name: cas-ggircs-metabase-preview
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          name: cas-ggircs-metabase-preview
      spec:
        containers:
        - capabilities: {}
          env:
          - name: MB_DB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: cas-ggircs-metabase-postgres
          - name: MB_DB_PASS
            valueFrom:
              secretKeyRef:
                key: database-password
                name: cas-ggircs-metabase-postgres
          - name: MB_DB_DBNAME
            valueFrom:
              secretKeyRef:
                key: database-name
                name: cas-ggircs-metabase-postgres
          - name: MB_DB_TYPE
            value: postgres
          - name: MB_DB_PORT
            value: "5432"
          - name: MB_DB_HOST
            value: cas-ggircs-metabase-postgres
          - name: JAVA_TIMEZONE
            value: US/Pacific
          image: cas-ggircs-metabase-mirror:${METABASE_VERSION}
          imagePullPolicy: IfNotPresent
          name: cas-ggircs-metabase
          ports:
          - containerPort: 3000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - cas-ggircs-metabase
        from:
          kind: ImageStreamTag
          name: cas-ggircs-metabase-mirror:${METABASE_VERSION}
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  status: {}

parameters:
- description: Git tag of the metabase version
  displayName: Metabase version
  name: METABASE_VERSION
  required: true
