{{- if .Values.app.route.ssl.enable }}

{{- $caServer := "https://acme-v02.api.letsencrypt.org/directory" }}

{{- if .Values.app.route.ssl.caServerSecret }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Values.app.route.ssl.caServerSecret ) }}
{{- $caServer = (index $secret.data .Values.app.route.ssl.caServerKey) | b64dec }}
{{- end -}}

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "cas-ggircs.fullname" . }}-acme-renewal
  labels: {{ include "cas-ggircs.labels" . | nindent 4 }}

spec:
  suspend: true # This cron job is intended to be triggered manually
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels: {{ include "cas-ggircs.labels" . | nindent 14 }}
        spec:
          restartPolicy: Never
          containers:
            - name: {{ template "cas-ggircs.fullname" . }}-acme-renewal
              image: bitnami/git
              resources:
                limits:
                  cpu: 1000m
                  memory: 128Mi
                requests:
                  cpu: 100m
                  memory: 64Mi
              command:
                - /usr/bin/env
                - bash
                - -c
                - |
                  set -euxo pipefail;
                  # renews the certificate if needed
                  /tmp/.acme.sh/acme.sh --cron --home /tmp/.acme.sh --server {{ $caServer }};
              volumeMounts:
                - mountPath: /tmp/.acme.sh
                  name: acme-home
                - mountPath: /tmp/.well-known/acme-challenge
                  name: acme-challenge
          volumes:
            - name: acme-home
              persistentVolumeClaim:
                claimName: {{ template "cas-ggircs.fullname" . }}-acme-home
            - name: acme-challenge
              persistentVolumeClaim:
                claimName: {{ template "cas-ggircs.fullname" . }}-acme-challenge
          imagePullSecrets:
            - name: dockerhub-registry
{{- end }}
