apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template

parameters:
- description: Prefix to prepend to object name.
  displayName: Prefix
  name: PREFIX
  required: true
- description: Version of PostgreSQL image to be used (10 for now).
  displayName: Version of PostgreSQL Image
  name: POSTGRES_VERSION
  required: true
  value: "latest"
- description: SHA1 of git revision to be deployed.
  displayName: Git SHA1
  name: GIT_SHA1
  required: true


envDefaults: &envDefaults
  env:
    - name: SQITCH_TARGET
      value: "db:pg:"
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: ${PREFIX}postgres
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: ${PREFIX}postgres
    - name: PGDATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: ${PREFIX}postgres
    - name: PGPORT
      value: "5432"
    - name: PGHOST
      value: ${PREFIX}postgres
    - name: SQITCH_FULLNAME
      value: OpenShift Deployer
    - name: SQITCH_EMAIL
      value: deployer@pathfinder.gov.bc.ca

objects:

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true"
    name: ${PREFIX}elt
  spec:
    replicas: 1
    selector:
      name: ${PREFIX}etl
    strategy:
      type: Recreate
      recreateParams:
        pre:
          failurePolicy: Retry
          execNewPod:
            <<: *envDefaults
            containerName: ${PREFIX}etl
            command:
              - /usr/bin/env
              - bash
              - -c
              - |
                sqitch revert swrs/extract/table/ghgr_import -y;
        post:
          failurePolicy: Retry
          execNewPod:
            <<: *envDefaults
            containerName: ${PREFIX}etl
            command:
              - /usr/bin/env
              - bash
              - -c
              - |
                set -euo pipefail;
                sqitch deploy;
                echo "Exporting data to 'swrs' schema";
                psql -c "select swrs_transform.load()";
    template:
      metadata:
        labels:
          name: ${PREFIX}etl
      spec:
        containers:
        - <<: *envDefaults
          image: ${PREFIX}etl:${GIT_SHA1}
          imagePullPolicy: IfNotPresent
          name: ${PREFIX}etl
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/app-root/src/data
            name: ${PREFIX}data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: ${PREFIX}data
          persistentVolumeClaim:
            claimName: ${PREFIX}data
    triggers: []
