{{- if .Values.swrsImportBucket.enable }}
kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ include "cas-ggircs.fullname" . }}-swrs-import-bucket-provider-egress
  labels: {{ include "cas-ggircs.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,hook-failed"
    "helm.sh/hook-weight": "-100"
spec:
  description: allow the swrs-import-bucket provider job within this release to communicate with external networks
  source:
    - - $namespace={{ .Release.Namespace }}
      - app.kubernetes.io/instance={{ include "cas-ggircs.name" . }}
  destination:
    - - ext:network=any
{{- end }}
