apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-postgres
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
      importPolicy:
        scheduled: false
      name: ${POSTGRES_VERSION}
    - from:
        kind: DockerImage
        name: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
      importPolicy:
        scheduled: false
      name: latest
  status: {}

parameters:

- description: Name of Postgres image to be used.
  displayName: Name of Postgres Image
  name: POSTGRES_IMAGE
  required: true
  value: "registry.access.redhat.com/rhscl/postgresql-10-rhel7"

- description: Version of Postgres image to be used.
  displayName: Version of Postgres Image
  name: POSTGRES_VERSION
  required: true
  value: "1-35"

