apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-metabase-mirror
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/wksv3k-tools/cas-ggircs-metabase:${GIT_SHA}
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
  status: {}

- description: Git source code commit currently deployed.
  displayName: Git Short sha
  name: GIT_SHA
  required: true

