apiVersion: template.openshift.io/v1
kind: Template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-mirror
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/wksv3k-tools/cas-ggircs:${GIT_SHA}
      name: ${GIT_SHA}
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/wksv3k-tools/cas-ggircs:${GIT_SHA}
      name: latest
  status: {}

parameters:
- description: Git source code commit currently deployed.
  displayName: Git Short sha
  name: GIT_SHA
  required: true

