apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: deploy-template
objects:

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-metabase-mirror
  spec:
    lookupPolicy:
      local: true
    tags:
    - from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/wksv3k-tools/cas-ggircs-metabase:${GIT_BRANCH_NORM}
      importPolicy:
        scheduled: true
      name: ${GIT_BRANCH_NORM}
      referencePolicy:
        type: Source
  status: {}

parameters:
- description: Git source code branch currently deployed, where slashes are replaced by dashes, to be able to use it in image tags.
  displayName: Git branch (normalized)
  name: GIT_BRANCH_NORM
  required: true
