apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: cas-ggircs-sqitch
    name: cas-ggircs-sqitch
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp: null
    labels:
      build: cas-ggircs-sqitch
    name: cas-ggircs-sqitch
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs-sqitch:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: docker/sqitch/
      git:
        uri: https://github.com/bcgov/cas-ggircs.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubuntu:xenial
          namespace: wksv3k-tools
      type: Docker
    triggers:
    - github:
        secret: nJNA0Dta3JpzPNWHqdEv
      type: GitHub
    - generic:
        secret: ab8MnpSOMOUKBn-jI94H
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
