apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: cas-ggircs:latest
    creationTimestamp: null
    labels:
      app: cas-ggircs
    name: cas-ggircs:latest
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: cas-ggircs:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: cas-ggircs
    name: cas-ggircs
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: feature/deploy
        uri: https://github.com/bcgov/cas-ggircs.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: perl:5.26
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: hoIKHObxOMxXV6sWEGP3
      type: GitHub
    - generic:
        secret: cUWe6a0LoEZ7zwgH1jXb
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: cas-ggircs
    name: cas-ggircs
  spec:
    replicas: 1
    selector:
      app: cas-ggircs
      deploymentconfig: cas-ggircs
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: cas-ggircs
          deploymentconfig: cas-ggircs
      spec:
        containers:
        - image: cas-ggircs:latest
          name: cas-ggircs
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - cas-ggircs
        from:
          kind: ImageStreamTag
          name: cas-ggircs:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: cas-ggircs
    name: cas-ggircs
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: cas-ggircs
      deploymentconfig: cas-ggircs
  status:
    loadBalancer: {}
kind: List
metadata: {}
