apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: cas-ggircs-build-config-template
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-perl
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${PERL_IMAGE}:${PERL_VERSION}
      generation: 1
      importPolicy:
        scheduled: true
      name: ${PERL_VERSION}
      referencePolicy:
        type: Source
  status: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs-postgres
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: ${POSTGRES_IMAGE}:${POSTGRES_VERSION}
      generation: 1
      importPolicy:
        scheduled: true
      name: ${POSTGRES_VERSION}
      referencePolicy:
        type: Source
  status: {}
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cas-ggircs
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cas-ggircs
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs:latest
    resources:
      limits:
        cpu: "4"
        memory: 8Gi
      requests:
        cpu: 100m
        memory: 256Mi
    source:
      git:
        ref: feature/deploy
        uri: https://github.com/bcgov/cas-ggircs.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: cas-ggircs-perl:${PERL_VERSION}
      type: Source
    triggers:
    - github:
        secret: cas-ggircs-github-trigger
      type: GitHub
    - generic:
        secret: cas-ggircs-generic-trigger
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
parameters:
- description: Name of Perl image to be used (perl-526-rhel7 for now).
  displayName: Name of Perl Image
  name: PERL_IMAGE
  required: true
  value: "registry.access.redhat.com/rhscl/perl-526-rhel7"
- description: Version of Perl image to be used (latest for now).
  displayName: Version of Perl Image
  name: PERL_VERSION
  required: true
  value: "latest"
- description: Name of Postgres image to be used (postgresql-10-rhel7 for now).
  displayName: Name of Postgres Image
  name: POSTGRES_IMAGE
  required: true
  value: "registry.access.redhat.com/rhscl/postgresql-10-rhel7"
- description: Version of Postgres image to be used (latest for now).
  displayName: Version of Postgres Image
  name: POSTGRES_VERSION
  required: true
  value: "latest"
