apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: 2019-05-14T17:49:46Z
  generation: 2
  labels:
    app: metabase-dev
  name: metabase-dev
  namespace: wksv3k-dev
  resourceVersion: "776223548"
  selfLink: /apis/apps.openshift.io/v1/namespaces/wksv3k-dev/deploymentconfigs/metabase-dev
  uid: a95b4424-7670-11e9-9558-0050568379a2
spec:
  replicas: 1
  selector:
    app: metabase-dev
    deploymentconfig: metabase-dev
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      creationTimestamp: null
      labels:
        app: metabase-dev
        deploymentconfig: metabase-dev
    spec:
      containers:
      - env:
        - name: MB_DB_TYPE
          value: postgres
        - name: MB_DB_DBNAME
          value: metabase
        - name: MB_DB_PORT
          value: "5432"
        - name: MB_DB_USER
          value: postgres
        - name: MB_DB_PASS
          value: postgres
        - name: MB_DB_HOST
          value: patroni-persistent-master
        - name: JAVA_TIMEZONE
          value: US/Pacific
        image: wenzowski/metabase@sha256:7b05362cd59f86a88038fa488d6bcfcb1d77da9064e7bd0918193ab2b4d80e9e
        imagePullPolicy: Always
        name: metabase-dev
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - metabase-dev
      from:
        kind: ImageStreamTag
        name: metabase-dev:latest
        namespace: wksv3k-tools
      lastTriggeredImage: wenzowski/metabase@sha256:7b05362cd59f86a88038fa488d6bcfcb1d77da9064e7bd0918193ab2b4d80e9e
    type: ImageChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-05-14T17:51:45Z
    lastUpdateTime: 2019-05-14T17:51:45Z
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: 2019-05-14T17:50:26Z
    lastUpdateTime: 2019-05-14T17:51:47Z
    message: replication controller "metabase-dev-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1
