apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    creationTimestamp: null
    labels:
      build: cas-ggircs
    name: cas-ggircs:latest
  tag:
    from:
      kind: DockerImage
      name: cas-ggircs:latest
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    labels:
      build: cas-ggircs
    name: cas-ggircs
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: cas-ggircs:latest
    postCommit: {}
    resources: {}
    source:
      git:
        ref: feature/deploy
        uri: git@github.com:bcgov/cas-ggircs.git
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ubuntu:xenial
          namespace: wksv3k-tools
      type: Docker
    triggers:
    - github:
        secret: gj4_eyWNM-_1Pu7BMpeO
      type: GitHub
    - generic:
        secret: 7EeUGDch7nXMLFuoTcfm
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
