apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cas-ggircs-data-migrate.fullname" . }}
  labels: {{ include "cas-ggircs-data-migrate.labels" . | nindent 4 }}
  # annotations:
  #   "helm.sh/hook": "pre-upgrade,pre-install"
  #   "helm.sh/hook-delete-policy": "before-hook-creation"
  #   "helm.sh/hook-weight": "-5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.storageClass }}
