-- Deploy ggircs:swrs/parameters/table/fuel_mapping to pg
-- requires: swrs/parameters/table/fuel_carbon_tax_detail

begin;

create table ggircs_parameters.fuel_mapping (
  id integer generated always as identity primary key,
  fuel_type varchar(1000),
  fuel_carbon_tax_detail_id integer references ggircs_parameters.fuel_carbon_tax_detail(id)
);

create index ggircs_parameters_fuel_mapping_ct_detail_foreign_key on ggircs_parameters.fuel_mapping(fuel_carbon_tax_detail_id);
create unique index ggircs_parameters_fuel_mapping_fuel_type on ggircs_parameters.fuel_mapping(fuel_type);

comment on table  ggircs_parameters.fuel_mapping is 'The fuel mapping table that maps all reported fuel types from swrs to a normalized fuel type with carbon tax details';
comment on column ggircs_parameters.fuel_mapping.id is 'The internal primary key for the mapping';
comment on column ggircs_parameters.fuel_mapping.fuel_type is 'The type of fuel (from GHGR), Foreign key to fuel';
comment on column ggircs_parameters.fuel_mapping.fuel_carbon_tax_detail_id is 'The foreign key to ggircs_parameters.fuel_carbon_tax_detail';


insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Acetylene', 1);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Acetylene (Sm^3)', 1);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Agricultural Byproducts (bone dry tonnes)', 2);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Anthracite Coal (tonnes)', 3);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Asphalt & Road Oil (kilolitres)', 4);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Aviation Gasoline (kilolitres)', 5);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Aviation Turbo Fuel (kilolitres)', 6);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Biodiesel (100)', 7);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Biodiesel (100) (kilolitres)', 7);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Biodiesel (100%) (kilolitres)', 7);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Biogas (captured methane) (Sm^3)', 8);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Bituminous Coal', 9);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Bituminous Coal (tonnes)', 9);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Bone char - organics', 10);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Bone char - organics (tonnes)', 10);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Butane (kilolitres)', 11);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Butylene (kilolitres)', 12);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('C/D Waste - Plastic (tonnes)', 13);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('C/D Waste - Wood (tonnes)', 14);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Cloth (tonnes)', 15);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('CNCG', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('CNCGs (Sm^3)', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Coal Coke (tonnes)', 17);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Coal/PetCoke  blend (tonnes)', 18);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Coke Oven Gas (Sm^3)', 19);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Combustible Tall Oil', 20);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Combustible Tall Oil (kilolitres)', 20);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated non-condensable gases (CNCGs)', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated Non-condensible Gas', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated Non-condensable Gases', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated Non-condensible Gases', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated Non-Condensible Gases (CNCG)', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated non-condensible gases (CNCGs)', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated non-condensible gases (CNCGs) (Sm^3)', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated non-condensible gases from kraft process', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Crude Oil (kilolitres)', 21);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Crude Sulfate Turpentine (CST)', 22);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Crude Sulfate Turpentine (CST) (kilolitres)', 22);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Crude Tall Oil (CTO)', 23);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Crude Tall Oil (CTO) (kilolitres)', 23);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Diesel', 24);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Diesel (kilolitres)', 24);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Digester Gas', 25);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Digester Gas (Sm^3)', 25);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Dilute non-condensable gases (DNCGs)', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Dilute Non-condensible Gas', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Dilute non-condensible gases (DNCGs)', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Dilute non-condensible gases (DNCGs) (Sm^3)', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Dilute non-condensible gases from kraft process', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Distilate Fuel Oil No.1', 26);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Distilate Fuel Oil No.1 (kilolitres)', 26);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Distilate Fuel Oil No.2', 27);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Distilate Fuel Oil No.2 (kilolitres)', 27);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Distilate Fuel Oil No.4 (kilolitres)', 28);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('DNCG', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('DNCG''s', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('DNCGs (Sm^3)', 29);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('E-Waste', 33);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('E-Waste (tonnes)', 33);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Ethane (kilolitres)', 30);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Ethanol (100%) (kilolitres)', 31);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Ethylene (kilolitres)', 32);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Explosives', 34);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Explosives (tonnes)', 34);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Field Gas', 36);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Field Gas (Sm^3)', 36);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Field gas or process vent gas', 35);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Field gas or process vent gas  (Sm^3)', 35);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Foreign Bituminous Coal (tonnes)', 37);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Isobutane (kilolitres)', 38);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Isobutylene (kilolitres)', 39);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Kerosene', 40);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Kerosene (kilolitres)', 40);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Kerosene-type Jet Fuel (kilolitres)', 41);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Landfill Gas', 42);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Landfill Gas (Sm^3)', 42);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Light Fuel Oil', 43);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Light Fuel Oil (kilolitres)', 43);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Lignite (tonnes)', 44);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Liquified Petroleum Gases (LPG)', 45);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Liquified Petroleum Gases (LPG) (kilolitres)', 45);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Lubricants', 46);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Lubricants (kilolitres)', 46);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Motor Gasoline', 47);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Motor Gasoline - Off-Road (kilolitres)', 48);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Motor Gasoline (kilolitres)', 47);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Municipal Solid Waste - biomas', 49);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Municipal Solid Waste - biomass component', 49);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Municipal Solid Waste - biomass component (bone dry tonnes)', 49);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Municipal Solid Waste - non-bi', 50);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Municipal Solid Waste - non-biomass component', 50);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Municipal Solid Waste - non-biomass component (tonnes)', 50);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Naphtha', 51);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Naphtha (kilolitres)', 51);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Natural Gas', 53);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Natural Gas (Sm^3)', 53);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Natural Gasoline', 52);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Natural Gasoline (kilolitres)', 52);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Nitrous Oxide', 54);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Nitrous Oxide (Sm^3)', 54);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Peat (tonnes)', 55);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('PEF (tonnes)', 56);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Petrochemical Feedstocks (kilolitres)', 57);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Petroleum Coke', 58);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Petroleum Coke - Refinery Use (kilolitres)', 59);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Petroleum Coke (kilolitres)', 58);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Plastic (tonnes)', 60);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Propane ', 61);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Propane', 61);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Propane (kilolitres)', 61);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Propylene (kilolitres)', 62);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Refinery Fuel Gas', 63);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Refinery Fuel Gas (Sm^3)', 63);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Rendered Animal Fat (kilolitres)', 64);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Residual Fuel Oil (#5 & 6)', 65);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Residual Fuel Oil (#5 & 6) (kilolitres)', 65);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('RFG - Mix Drum', 66);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('RFG - Reformer Gas', 67);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Roofing Tear-off (tonnes)', 68);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('SMR PSA Tail Gas', 69);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('SMR PSA Tail Gas (Sm^3)', 69);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Sodium Bicarbonate', 70);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Sodium Bicarbonate (tonnes)', 70);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Solid Byproducts', 71);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Solid Byproducts (bone dry tonnes)', 71);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Spent Pulping Liquor', 72);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Spent Pulping Liquor (bone dry tonnes)', 72);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Still Gas', 74);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Still Gas - Refineries (Sm^3)', 73);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Still Gas (Sm^3)', 74);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Sub-Bituminous Coal', 75);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Sub-Bituminous Coal (tonnes)', 75);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Tail Gas (Sm^3)', 76);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Tall Oil (kilolitres)', 77);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Tires - biomass component (bone dry tonnes)', 78);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Tires - non-biomass component', 79);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Tires - non-biomass component (tonnes)', 79);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Trona (tonnes)', 80);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Turpentine', 81);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Turpentine (kilolitres)', 81);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Vegetable Oil (kilolitres)', 82);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Waste Oil (kilolitres)', 83);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Wood Waste', 84);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Wood Waste (bone dry tonnes)', 84);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Flared Natural Gas CO2', 85);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Vented Natural Gas CH4', 86);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('ANFO', 43);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated Non-Condensable Gases', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Field gas', 36);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Gasoline', 47);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Process vent gas', 53);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Concentrated Non-Condensible Gases (CNCG) (Sm^3)', 16);
insert into ggircs_parameters.fuel_mapping (fuel_type, fuel_carbon_tax_detail_id) values ('Carpet fibre (tonnes)', 87);

commit;
