name: Build Containers

on:
  push:
    branches-ignore:
      - main
      - master
  schedule:
    - cron: "45 0 * * *"

jobs:
  ghg-issuer-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v4.1.0
        with:
          gcloud_service_key: ${{ secrets.GCR_KEY }}
          project_id: ggl-cas-storage
          image_name: ghg-credentials-issuer
          image_tag: latest,${{ github.sha }}
          dockerfile: ghg-credentials-issuer/Dockerfile
          context: ghg-credentials-issuer
  yarn-audit:
    needs: install-dev-tools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: dev env setup
        uses: ./.github/actions/dev-env-setup
      - run: yarn audit-deps
        working-directory: ./app
