name: Test sqitch changes immutability

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  check_immutable_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: ./.bin/sqitch-check-immutable-files.sh . origin/master
      - run: ./.bin/sqitch-check-immutable-files.sh ggircs-app/schema origin/master
